name: Deploy to Heroku
on:
  push:
    branches:
      - master
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: sbt stage deployHeroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_TOKEN }}

      