name: Deploy to Heroku
on:
  push:
    branches:
      - master
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
        - name: Scala SBT Action
          uses: matankdr/github-docker-sbt@openjdk8_alpine_sbt1_3_8_2
          with:
            command: sbt stage deployHeroku
      